#pragma once
#include "unicos.p"
#include "src/make_unicos.h"
#include "src/free_unicos.h"
#include "src/copy_unicos.h"
#include "src/extend_unicos.h"
#include "src/put_unicos.h"
#include "src/slice_unicos.h"
#include "src/concat_unicos.h"
