
all:

update:
	make -C script update
	make downcase_size_unicos_in.c
	make upcase_size_unicos_in.c
	make foldcase_size_unicos_in.c
	make titlecase_size_unicos_in.c
	make normalize_nfc_size_unicos_in.c
	make normalize_nfd_size_unicos_in.c
	make normalize_nfkc_size_unicos_in.c
	make normalize_nfkd_size_unicos_in.c
	make downcase_unicos_manually_in.c
	make upcase_unicos_manually_in.c
	make foldcase_unicos_manually_in.c
	make titlecase_unicos_manually_in.c
	make normalize_nfc_unicos_manually_in.c
	make normalize_nfd_unicos_manually_in.c
	make normalize_nfkc_unicos_manually_in.c
	make normalize_nfkd_unicos_manually_in.c
	make is_downcase_unicos_in.c
	make is_upcase_unicos_in.c
	make is_foldcase_unicos_in.c
	make is_titlecase_unicos_in.c
	make is_normalize_nfc_unicos_in.c
	make is_normalize_nfd_unicos_in.c
	make is_normalize_nfkc_unicos_in.c
	make is_normalize_nfkd_unicos_in.c

downcase_size_unicos_in.c: script/dist/downcase_size_unicos_in.c
	cp script/dist/downcase_size_unicos_in.c downcase_size_unicos_in.c

upcase_size_unicos_in.c: script/dist/upcase_size_unicos_in.c
	cp script/dist/upcase_size_unicos_in.c upcase_size_unicos_in.c

foldcase_size_unicos_in.c: script/dist/foldcase_size_unicos_in.c
	cp script/dist/foldcase_size_unicos_in.c foldcase_size_unicos_in.c

titlecase_size_unicos_in.c: script/dist/titlecase_size_unicos_in.c
	cp script/dist/titlecase_size_unicos_in.c titlecase_size_unicos_in.c

normalize_nfc_size_unicos_in.c: script/dist/normalize_nfc_size_unicos_in.c
	cp script/dist/normalize_nfc_size_unicos_in.c normalize_nfc_size_unicos_in.c

normalize_nfd_size_unicos_in.c: script/dist/normalize_nfd_size_unicos_in.c
	cp script/dist/normalize_nfd_size_unicos_in.c normalize_nfd_size_unicos_in.c

normalize_nfkc_size_unicos_in.c: script/dist/normalize_nfkc_size_unicos_in.c
	cp script/dist/normalize_nfkc_size_unicos_in.c normalize_nfkc_size_unicos_in.c

normalize_nfkd_size_unicos_in.c: script/dist/normalize_nfkd_size_unicos_in.c
	cp script/dist/normalize_nfkd_size_unicos_in.c normalize_nfkd_size_unicos_in.c

downcase_unicos_manually_in.c: script/dist/downcase_unicos_manually_in.c
	cp script/dist/downcase_unicos_manually_in.c downcase_unicos_manually_in.c

upcase_unicos_manually_in.c: script/dist/upcase_unicos_manually_in.c
	cp script/dist/upcase_unicos_manually_in.c upcase_unicos_manually_in.c

foldcase_unicos_manually_in.c: script/dist/foldcase_unicos_manually_in.c
	cp script/dist/foldcase_unicos_manually_in.c foldcase_unicos_manually_in.c
	
titlecase_unicos_manually_in.c: script/dist/titlecase_unicos_manually_in.c
	cp script/dist/titlecase_unicos_manually_in.c titlecase_unicos_manually_in.c

normalize_nfc_unicos_manually_in.c: script/dist/normalize_nfc_unicos_manually_in.c
	cp script/dist/normalize_nfc_unicos_manually_in.c normalize_nfc_unicos_manually_in.c

normalize_nfd_unicos_manually_in.c: script/dist/normalize_nfd_unicos_manually_in.c
	cp script/dist/normalize_nfd_unicos_manually_in.c normalize_nfd_unicos_manually_in.c

normalize_nfkc_unicos_manually_in.c: script/dist/normalize_nfkc_unicos_manually_in.c
	cp script/dist/normalize_nfkc_unicos_manually_in.c normalize_nfkc_unicos_manually_in.c

normalize_nfkd_unicos_manually_in.c: script/dist/normalize_nfkd_unicos_manually_in.c
	cp script/dist/normalize_nfkd_unicos_manually_in.c normalize_nfkd_unicos_manually_in.c

is_downcase_unicos_in.c: script/dist/is_downcase_unicos_in.c
	cp script/dist/is_downcase_unicos_in.c is_downcase_unicos_in.c

is_upcase_unicos_in.c: script/dist/is_upcase_unicos_in.c
	cp script/dist/is_upcase_unicos_in.c is_upcase_unicos_in.c

is_foldcase_unicos_in.c: script/dist/is_foldcase_unicos_in.c
	cp script/dist/is_foldcase_unicos_in.c is_foldcase_unicos_in.c
	
is_titlecase_unicos_in.c: script/dist/is_titlecase_unicos_in.c
	cp script/dist/is_titlecase_unicos_in.c is_titlecase_unicos_in.c

is_normalize_nfc_unicos_in.c: script/dist/is_normalize_nfc_unicos_in.c
	cp script/dist/is_normalize_nfc_unicos_in.c is_normalize_nfc_unicos_in.c

is_normalize_nfd_unicos_in.c: script/dist/is_normalize_nfd_unicos_in.c
	cp script/dist/is_normalize_nfd_unicos_in.c is_normalize_nfd_unicos_in.c

is_normalize_nfkc_unicos_in.c: script/dist/is_normalize_nfkc_unicos_in.c
	cp script/dist/is_normalize_nfkc_unicos_in.c is_normalize_nfkc_unicos_in.c

is_normalize_nfkd_unicos_in.c: script/dist/is_normalize_nfkd_unicos_in.c
	cp script/dist/is_normalize_nfkd_unicos_in.c is_normalize_nfkd_unicos_in.c
