all:

update: 
	make dist/is_adlam_unicos.c
	make dist/is_ahom_unicos.c
	make dist/is_anatolian_hieroglyphs_unicos.c
	make dist/is_arabic_unicos.c
	make dist/is_armenian_unicos.c
	make dist/is_avestan_unicos.c
	make dist/is_balinese_unicos.c
	make dist/is_bamum_unicos.c
	make dist/is_bassa_vah_unicos.c
	make dist/is_batak_unicos.c
	make dist/is_bengali_unicos.c
	make dist/is_bhaiksuki_unicos.c
	make dist/is_bopomofo_unicos.c
	make dist/is_brahmi_unicos.c
	make dist/is_buginese_unicos.c
	make dist/is_buhid_unicos.c
	make dist/is_canadian_aboriginal_unicos.c
	make dist/is_carian_unicos.c
	make dist/is_caucasian_albanian_unicos.c
	make dist/is_chakma_unicos.c
	make dist/is_cham_unicos.c
	make dist/is_cherokee_unicos.c
	make dist/is_cjk_unicos.c
	make dist/is_cjk_extensions_unicos.c
	make dist/is_coptic_unicos.c
	make dist/is_cuneiform_unicos.c
	make dist/is_currency_symbol_unicos.c
	make dist/is_cypriot_unicos.c
	make dist/is_cyrillic_unicos.c
	make dist/is_deseret_unicos.c
	make dist/is_devanagari_unicos.c
	make dist/is_digits_unicos.c
	make dist/is_duployan_unicos.c
	make dist/is_egyptian_hieroglyphs_unicos.c
	make dist/is_elbasan_unicos.c
	make dist/is_ethiopic_unicos.c
	make dist/is_general_symbol_unicos.c
	make dist/is_georgian_unicos.c
	make dist/is_glagolitic_unicos.c
	make dist/is_gothic_unicos.c
	make dist/is_grantha_unicos.c
	make dist/is_greek_unicos.c
	make dist/is_gujarati_unicos.c
	make dist/is_gurmukhi_unicos.c
	make dist/is_hangul_unicos.c
	make dist/is_hanunoo_unicos.c
	make dist/is_hatran_unicos.c
	make dist/is_hebrew_unicos.c
	make dist/is_ignored_unicos.c
	make dist/is_imperial_aramaic_unicos.c
	make dist/is_inscriptional_pahlavi_unicos.c
	make dist/is_inscriptional_parthian_unicos.c
	make dist/is_javanese_unicos.c
	make dist/is_kaithi_unicos.c
	make dist/is_kannada_unicos.c
	make dist/is_katakana_and_hiragana_unicos.c
	make dist/is_kayah_li_unicos.c
	make dist/is_kharoshthi_unicos.c
	make dist/is_khmer_unicos.c
	make dist/is_khojki_unicos.c
	make dist/is_khudawadi_unicos.c
	make dist/is_lao_unicos.c
	make dist/is_latin_unicos.c
	make dist/is_lepcha_unicos.c
	make dist/is_limbu_unicos.c
	make dist/is_linear_a_unicos.c
	make dist/is_linear_b_unicos.c
	make dist/is_lisu_unicos.c
	make dist/is_lycian_unicos.c
	make dist/is_lydian_unicos.c
	make dist/is_mahajani_unicos.c
	make dist/is_malayalam_unicos.c
	make dist/is_mandaic_unicos.c
	make dist/is_manichaean_unicos.c
	make dist/is_marchen_unicos.c
	make dist/is_masaram_gondi_unicos.c
	make dist/is_meetei_mayek_unicos.c
	make dist/is_mende_kikakui_unicos.c
	make dist/is_meroitic_hieroglyphs_and_cursive_unicos.c
	make dist/is_miao_unicos.c
	make dist/is_modi_unicos.c
	make dist/is_mongolian_unicos.c
	make dist/is_mro_unicos.c
	make dist/is_multani_unicos.c
	make dist/is_myanmar_unicos.c
	make dist/is_nabataean_unicos.c
	make dist/is_newa_unicos.c
	make dist/is_new_tai_lue_unicos.c
	make dist/is_nko_unicos.c
	make dist/is_nushu_unicos.c
	make dist/is_ogham_unicos.c
	make dist/is_old_hungarian_unicos.c
	make dist/is_old_italic_unicos.c
	make dist/is_old_north_arabian_unicos.c
	make dist/is_old_permic_unicos.c
	make dist/is_old_persian_unicos.c
	make dist/is_old_south_arabian_unicos.c
	make dist/is_old_turkic_unicos.c
	make dist/is_ol_chiki_unicos.c
	make dist/is_oriya_unicos.c
	make dist/is_osage_unicos.c
	make dist/is_osmanya_unicos.c
	make dist/is_pahawh_hmong_unicos.c
	make dist/is_palmyrene_unicos.c
	make dist/is_pau_cin_hau_unicos.c
	make dist/is_phags_pa_unicos.c
	make dist/is_phoenician_unicos.c
	make dist/is_psalter_pahlavi_unicos.c
	make dist/is_punctuation_unicos.c
	make dist/is_rejang_unicos.c
	make dist/is_runic_unicos.c
	make dist/is_samaritan_unicos.c
	make dist/is_saurashtra_unicos.c
	make dist/is_secondary_unicos.c
	make dist/is_sharada_unicos.c
	make dist/is_shavian_unicos.c
	make dist/is_siddham_unicos.c
	make dist/is_sinhala_unicos.c
	make dist/is_sora_sompeng_unicos.c
	make dist/is_soyombo_unicos.c
	make dist/is_sundanese_unicos.c
	make dist/is_syloti_nagri_unicos.c
	make dist/is_syriac_unicos.c
	make dist/is_tagalog_unicos.c
	make dist/is_tagbanwa_unicos.c
	make dist/is_tai_le_unicos.c
	make dist/is_tai_tham_unicos.c
	make dist/is_tai_viet_unicos.c
	make dist/is_takri_unicos.c
	make dist/is_tamil_unicos.c
	make dist/is_tangut_unicos.c
	make dist/is_telugu_unicos.c
	make dist/is_thaana_unicos.c
	make dist/is_thai_unicos.c
	make dist/is_tibetan_unicos.c
	make dist/is_tifinagh_unicos.c
	make dist/is_tirhuta_unicos.c
	make dist/is_ugaritic_unicos.c
	make dist/is_unsupported_unicos.c
	make dist/is_vai_unicos.c
	make dist/is_warang_citi_unicos.c
	make dist/is_whitespace_unicos.c
	make dist/is_yi_unicos.c
	make dist/is_zanabazar_square_unicos.c

dist/is_adlam_unicos.c: is_adlam_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/adlam.json
	$(PYTHON) is_adlam_unicos.py

dist/is_ahom_unicos.c: is_ahom_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/ahom.json
	$(PYTHON) is_ahom_unicos.py

dist/is_anatolian_hieroglyphs_unicos.c: is_anatolian_hieroglyphs_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/anatolian_hieroglyphs.json
	$(PYTHON) is_anatolian_hieroglyphs_unicos.py

dist/is_arabic_unicos.c: is_arabic_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/arabic.json
	$(PYTHON) is_arabic_unicos.py

dist/is_armenian_unicos.c: is_armenian_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/armenian.json
	$(PYTHON) is_armenian_unicos.py

dist/is_avestan_unicos.c: is_avestan_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/avestan.json
	$(PYTHON) is_avestan_unicos.py

dist/is_balinese_unicos.c: is_balinese_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/balinese.json
	$(PYTHON) is_balinese_unicos.py

dist/is_bamum_unicos.c: is_bamum_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/bamum.json
	$(PYTHON) is_bamum_unicos.py

dist/is_bassa_vah_unicos.c: is_bassa_vah_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/bassa_vah.json
	$(PYTHON) is_bassa_vah_unicos.py

dist/is_batak_unicos.c: is_batak_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/batak.json
	$(PYTHON) is_batak_unicos.py

dist/is_bengali_unicos.c: is_bengali_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/bengali.json
	$(PYTHON) is_bengali_unicos.py

dist/is_bhaiksuki_unicos.c: is_bhaiksuki_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/bhaiksuki.json
	$(PYTHON) is_bhaiksuki_unicos.py

dist/is_bopomofo_unicos.c: is_bopomofo_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/bopomofo.json
	$(PYTHON) is_bopomofo_unicos.py

dist/is_brahmi_unicos.c: is_brahmi_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/brahmi.json
	$(PYTHON) is_brahmi_unicos.py

dist/is_buginese_unicos.c: is_buginese_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/buginese.json
	$(PYTHON) is_buginese_unicos.py

dist/is_buhid_unicos.c: is_buhid_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/buhid.json
	$(PYTHON) is_buhid_unicos.py

dist/is_canadian_aboriginal_unicos.c: is_canadian_aboriginal_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/canadian_aboriginal.json
	$(PYTHON) is_canadian_aboriginal_unicos.py

dist/is_carian_unicos.c: is_carian_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/carian.json
	$(PYTHON) is_carian_unicos.py

dist/is_caucasian_albanian_unicos.c: is_caucasian_albanian_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/caucasian_albanian.json
	$(PYTHON) is_caucasian_albanian_unicos.py

dist/is_chakma_unicos.c: is_chakma_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/chakma.json
	$(PYTHON) is_chakma_unicos.py

dist/is_cham_unicos.c: is_cham_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/cham.json
	$(PYTHON) is_cham_unicos.py

dist/is_cherokee_unicos.c: is_cherokee_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/cherokee.json
	$(PYTHON) is_cherokee_unicos.py

dist/is_cjk_unicos.c: is_cjk_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/cjk.json
	$(PYTHON) is_cjk_unicos.py

dist/is_cjk_extensions_unicos.c: is_cjk_extensions_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/cjk_extensions.json
	$(PYTHON) is_cjk_extensions_unicos.py

dist/is_coptic_unicos.c: is_coptic_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/coptic.json
	$(PYTHON) is_coptic_unicos.py

dist/is_cuneiform_unicos.c: is_cuneiform_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/cuneiform.json
	$(PYTHON) is_cuneiform_unicos.py

dist/is_currency_symbol_unicos.c: is_currency_symbol_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/currency_symbol.json
	$(PYTHON) is_currency_symbol_unicos.py

dist/is_cypriot_unicos.c: is_cypriot_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/cypriot.json
	$(PYTHON) is_cypriot_unicos.py

dist/is_cyrillic_unicos.c: is_cyrillic_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/cyrillic.json
	$(PYTHON) is_cyrillic_unicos.py

dist/is_deseret_unicos.c: is_deseret_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/deseret.json
	$(PYTHON) is_deseret_unicos.py

dist/is_devanagari_unicos.c: is_devanagari_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/devanagari.json
	$(PYTHON) is_devanagari_unicos.py

dist/is_digits_unicos.c: is_digits_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/digits.json
	$(PYTHON) is_digits_unicos.py

dist/is_duployan_unicos.c: is_duployan_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/duployan.json
	$(PYTHON) is_duployan_unicos.py

dist/is_egyptian_hieroglyphs_unicos.c: is_egyptian_hieroglyphs_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/egyptian_hieroglyphs.json
	$(PYTHON) is_egyptian_hieroglyphs_unicos.py

dist/is_elbasan_unicos.c: is_elbasan_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/elbasan.json
	$(PYTHON) is_elbasan_unicos.py

dist/is_ethiopic_unicos.c: is_ethiopic_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/ethiopic.json
	$(PYTHON) is_ethiopic_unicos.py

dist/is_general_symbol_unicos.c: is_general_symbol_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/general_symbol.json
	$(PYTHON) is_general_symbol_unicos.py

dist/is_georgian_unicos.c: is_georgian_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/georgian.json
	$(PYTHON) is_georgian_unicos.py

dist/is_glagolitic_unicos.c: is_glagolitic_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/glagolitic.json
	$(PYTHON) is_glagolitic_unicos.py

dist/is_gothic_unicos.c: is_gothic_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/gothic.json
	$(PYTHON) is_gothic_unicos.py

dist/is_grantha_unicos.c: is_grantha_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/grantha.json
	$(PYTHON) is_grantha_unicos.py

dist/is_greek_unicos.c: is_greek_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/greek.json
	$(PYTHON) is_greek_unicos.py

dist/is_gujarati_unicos.c: is_gujarati_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/gujarati.json
	$(PYTHON) is_gujarati_unicos.py

dist/is_gurmukhi_unicos.c: is_gurmukhi_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/gurmukhi.json
	$(PYTHON) is_gurmukhi_unicos.py

dist/is_hangul_unicos.c: is_hangul_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/hangul.json
	$(PYTHON) is_hangul_unicos.py

dist/is_hanunoo_unicos.c: is_hanunoo_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/hanunoo.json
	$(PYTHON) is_hanunoo_unicos.py

dist/is_hatran_unicos.c: is_hatran_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/hatran.json
	$(PYTHON) is_hatran_unicos.py

dist/is_hebrew_unicos.c: is_hebrew_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/hebrew.json
	$(PYTHON) is_hebrew_unicos.py

dist/is_ignored_unicos.c: is_ignored_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/ignored.json
	$(PYTHON) is_ignored_unicos.py

dist/is_imperial_aramaic_unicos.c: is_imperial_aramaic_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/imperial_aramaic.json
	$(PYTHON) is_imperial_aramaic_unicos.py

dist/is_inscriptional_pahlavi_unicos.c: is_inscriptional_pahlavi_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/inscriptional_pahlavi.json
	$(PYTHON) is_inscriptional_pahlavi_unicos.py

dist/is_inscriptional_parthian_unicos.c: is_inscriptional_parthian_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/inscriptional_parthian.json
	$(PYTHON) is_inscriptional_parthian_unicos.py

dist/is_javanese_unicos.c: is_javanese_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/javanese.json
	$(PYTHON) is_javanese_unicos.py

dist/is_kaithi_unicos.c: is_kaithi_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/kaithi.json
	$(PYTHON) is_kaithi_unicos.py

dist/is_kannada_unicos.c: is_kannada_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/kannada.json
	$(PYTHON) is_kannada_unicos.py

dist/is_katakana_and_hiragana_unicos.c: is_katakana_and_hiragana_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/katakana_and_hiragana.json
	$(PYTHON) is_katakana_and_hiragana_unicos.py

dist/is_kayah_li_unicos.c: is_kayah_li_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/kayah_li.json
	$(PYTHON) is_kayah_li_unicos.py

dist/is_kharoshthi_unicos.c: is_kharoshthi_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/kharoshthi.json
	$(PYTHON) is_kharoshthi_unicos.py

dist/is_khmer_unicos.c: is_khmer_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/khmer.json
	$(PYTHON) is_khmer_unicos.py

dist/is_khojki_unicos.c: is_khojki_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/khojki.json
	$(PYTHON) is_khojki_unicos.py

dist/is_khudawadi_unicos.c: is_khudawadi_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/khudawadi.json
	$(PYTHON) is_khudawadi_unicos.py

dist/is_lao_unicos.c: is_lao_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/lao.json
	$(PYTHON) is_lao_unicos.py

dist/is_latin_unicos.c: is_latin_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/latin.json
	$(PYTHON) is_latin_unicos.py

dist/is_lepcha_unicos.c: is_lepcha_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/lepcha.json
	$(PYTHON) is_lepcha_unicos.py

dist/is_limbu_unicos.c: is_limbu_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/limbu.json
	$(PYTHON) is_limbu_unicos.py

dist/is_linear_a_unicos.c: is_linear_a_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/linear_a.json
	$(PYTHON) is_linear_a_unicos.py

dist/is_linear_b_unicos.c: is_linear_b_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/linear_b.json
	$(PYTHON) is_linear_b_unicos.py

dist/is_lisu_unicos.c: is_lisu_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/lisu.json
	$(PYTHON) is_lisu_unicos.py

dist/is_lycian_unicos.c: is_lycian_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/lycian.json
	$(PYTHON) is_lycian_unicos.py

dist/is_lydian_unicos.c: is_lydian_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/lydian.json
	$(PYTHON) is_lydian_unicos.py

dist/is_mahajani_unicos.c: is_mahajani_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/mahajani.json
	$(PYTHON) is_mahajani_unicos.py

dist/is_malayalam_unicos.c: is_malayalam_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/malayalam.json
	$(PYTHON) is_malayalam_unicos.py

dist/is_mandaic_unicos.c: is_mandaic_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/mandaic.json
	$(PYTHON) is_mandaic_unicos.py

dist/is_manichaean_unicos.c: is_manichaean_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/manichaean.json
	$(PYTHON) is_manichaean_unicos.py

dist/is_marchen_unicos.c: is_marchen_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/marchen.json
	$(PYTHON) is_marchen_unicos.py

dist/is_masaram_gondi_unicos.c: is_masaram_gondi_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/masaram_gondi.json
	$(PYTHON) is_masaram_gondi_unicos.py

dist/is_meetei_mayek_unicos.c: is_meetei_mayek_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/meetei_mayek.json
	$(PYTHON) is_meetei_mayek_unicos.py

dist/is_mende_kikakui_unicos.c: is_mende_kikakui_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/mende_kikakui.json
	$(PYTHON) is_mende_kikakui_unicos.py

dist/is_meroitic_hieroglyphs_and_cursive_unicos.c: is_meroitic_hieroglyphs_and_cursive_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/meroitic_hieroglyphs_and_cursive.json
	$(PYTHON) is_meroitic_hieroglyphs_and_cursive_unicos.py

dist/is_miao_unicos.c: is_miao_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/miao.json
	$(PYTHON) is_miao_unicos.py

dist/is_modi_unicos.c: is_modi_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/modi.json
	$(PYTHON) is_modi_unicos.py

dist/is_mongolian_unicos.c: is_mongolian_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/mongolian.json
	$(PYTHON) is_mongolian_unicos.py

dist/is_mro_unicos.c: is_mro_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/mro.json
	$(PYTHON) is_mro_unicos.py

dist/is_multani_unicos.c: is_multani_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/multani.json
	$(PYTHON) is_multani_unicos.py

dist/is_myanmar_unicos.c: is_myanmar_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/myanmar.json
	$(PYTHON) is_myanmar_unicos.py

dist/is_nabataean_unicos.c: is_nabataean_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/nabataean.json
	$(PYTHON) is_nabataean_unicos.py

dist/is_newa_unicos.c: is_newa_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/newa.json
	$(PYTHON) is_newa_unicos.py

dist/is_new_tai_lue_unicos.c: is_new_tai_lue_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/new_tai_lue.json
	$(PYTHON) is_new_tai_lue_unicos.py

dist/is_nko_unicos.c: is_nko_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/nko.json
	$(PYTHON) is_nko_unicos.py

dist/is_nushu_unicos.c: is_nushu_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/nushu.json
	$(PYTHON) is_nushu_unicos.py

dist/is_ogham_unicos.c: is_ogham_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/ogham.json
	$(PYTHON) is_ogham_unicos.py

dist/is_old_hungarian_unicos.c: is_old_hungarian_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/old_hungarian.json
	$(PYTHON) is_old_hungarian_unicos.py

dist/is_old_italic_unicos.c: is_old_italic_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/old_italic.json
	$(PYTHON) is_old_italic_unicos.py

dist/is_old_north_arabian_unicos.c: is_old_north_arabian_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/old_north_arabian.json
	$(PYTHON) is_old_north_arabian_unicos.py

dist/is_old_permic_unicos.c: is_old_permic_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/old_permic.json
	$(PYTHON) is_old_permic_unicos.py

dist/is_old_persian_unicos.c: is_old_persian_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/old_persian.json
	$(PYTHON) is_old_persian_unicos.py

dist/is_old_south_arabian_unicos.c: is_old_south_arabian_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/old_south_arabian.json
	$(PYTHON) is_old_south_arabian_unicos.py

dist/is_old_turkic_unicos.c: is_old_turkic_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/old_turkic.json
	$(PYTHON) is_old_turkic_unicos.py

dist/is_ol_chiki_unicos.c: is_ol_chiki_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/ol_chiki.json
	$(PYTHON) is_ol_chiki_unicos.py

dist/is_oriya_unicos.c: is_oriya_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/oriya.json
	$(PYTHON) is_oriya_unicos.py

dist/is_osage_unicos.c: is_osage_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/osage.json
	$(PYTHON) is_osage_unicos.py

dist/is_osmanya_unicos.c: is_osmanya_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/osmanya.json
	$(PYTHON) is_osmanya_unicos.py

dist/is_pahawh_hmong_unicos.c: is_pahawh_hmong_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/pahawh_hmong.json
	$(PYTHON) is_pahawh_hmong_unicos.py

dist/is_palmyrene_unicos.c: is_palmyrene_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/palmyrene.json
	$(PYTHON) is_palmyrene_unicos.py

dist/is_pau_cin_hau_unicos.c: is_pau_cin_hau_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/pau_cin_hau.json
	$(PYTHON) is_pau_cin_hau_unicos.py

dist/is_phags_pa_unicos.c: is_phags_pa_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/phags_pa.json
	$(PYTHON) is_phags_pa_unicos.py

dist/is_phoenician_unicos.c: is_phoenician_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/phoenician.json
	$(PYTHON) is_phoenician_unicos.py

dist/is_psalter_pahlavi_unicos.c: is_psalter_pahlavi_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/psalter_pahlavi.json
	$(PYTHON) is_psalter_pahlavi_unicos.py

dist/is_punctuation_unicos.c: is_punctuation_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/punctuation.json
	$(PYTHON) is_punctuation_unicos.py

dist/is_rejang_unicos.c: is_rejang_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/rejang.json
	$(PYTHON) is_rejang_unicos.py

dist/is_runic_unicos.c: is_runic_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/runic.json
	$(PYTHON) is_runic_unicos.py

dist/is_samaritan_unicos.c: is_samaritan_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/samaritan.json
	$(PYTHON) is_samaritan_unicos.py

dist/is_saurashtra_unicos.c: is_saurashtra_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/saurashtra.json
	$(PYTHON) is_saurashtra_unicos.py

dist/is_secondary_unicos.c: is_secondary_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/secondary.json
	$(PYTHON) is_secondary_unicos.py

dist/is_sharada_unicos.c: is_sharada_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/sharada.json
	$(PYTHON) is_sharada_unicos.py

dist/is_shavian_unicos.c: is_shavian_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/shavian.json
	$(PYTHON) is_shavian_unicos.py

dist/is_siddham_unicos.c: is_siddham_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/siddham.json
	$(PYTHON) is_siddham_unicos.py

dist/is_sinhala_unicos.c: is_sinhala_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/sinhala.json
	$(PYTHON) is_sinhala_unicos.py

dist/is_sora_sompeng_unicos.c: is_sora_sompeng_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/sora_sompeng.json
	$(PYTHON) is_sora_sompeng_unicos.py

dist/is_soyombo_unicos.c: is_soyombo_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/soyombo.json
	$(PYTHON) is_soyombo_unicos.py

dist/is_sundanese_unicos.c: is_sundanese_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/sundanese.json
	$(PYTHON) is_sundanese_unicos.py

dist/is_syloti_nagri_unicos.c: is_syloti_nagri_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/syloti_nagri.json
	$(PYTHON) is_syloti_nagri_unicos.py

dist/is_syriac_unicos.c: is_syriac_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/syriac.json
	$(PYTHON) is_syriac_unicos.py

dist/is_tagalog_unicos.c: is_tagalog_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/tagalog.json
	$(PYTHON) is_tagalog_unicos.py

dist/is_tagbanwa_unicos.c: is_tagbanwa_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/tagbanwa.json
	$(PYTHON) is_tagbanwa_unicos.py

dist/is_tai_le_unicos.c: is_tai_le_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/tai_le.json
	$(PYTHON) is_tai_le_unicos.py

dist/is_tai_tham_unicos.c: is_tai_tham_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/tai_tham.json
	$(PYTHON) is_tai_tham_unicos.py

dist/is_tai_viet_unicos.c: is_tai_viet_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/tai_viet.json
	$(PYTHON) is_tai_viet_unicos.py

dist/is_takri_unicos.c: is_takri_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/takri.json
	$(PYTHON) is_takri_unicos.py

dist/is_tamil_unicos.c: is_tamil_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/tamil.json
	$(PYTHON) is_tamil_unicos.py

dist/is_tangut_unicos.c: is_tangut_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/tangut.json
	$(PYTHON) is_tangut_unicos.py

dist/is_telugu_unicos.c: is_telugu_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/telugu.json
	$(PYTHON) is_telugu_unicos.py

dist/is_thaana_unicos.c: is_thaana_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/thaana.json
	$(PYTHON) is_thaana_unicos.py

dist/is_thai_unicos.c: is_thai_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/thai.json
	$(PYTHON) is_thai_unicos.py

dist/is_tibetan_unicos.c: is_tibetan_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/tibetan.json
	$(PYTHON) is_tibetan_unicos.py

dist/is_tifinagh_unicos.c: is_tifinagh_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/tifinagh.json
	$(PYTHON) is_tifinagh_unicos.py

dist/is_tirhuta_unicos.c: is_tirhuta_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/tirhuta.json
	$(PYTHON) is_tirhuta_unicos.py

dist/is_ugaritic_unicos.c: is_ugaritic_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/ugaritic.json
	$(PYTHON) is_ugaritic_unicos.py

dist/is_unsupported_unicos.c: is_unsupported_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/unsupported.json
	$(PYTHON) is_unsupported_unicos.py

dist/is_vai_unicos.c: is_vai_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/vai.json
	$(PYTHON) is_vai_unicos.py

dist/is_warang_citi_unicos.c: is_warang_citi_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/warang_citi.json
	$(PYTHON) is_warang_citi_unicos.py

dist/is_whitespace_unicos.c: is_whitespace_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/whitespace.json
	$(PYTHON) is_whitespace_unicos.py

dist/is_yi_unicos.c: is_yi_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/yi.json
	$(PYTHON) is_yi_unicos.py

dist/is_zanabazar_square_unicos.c: is_zanabazar_square_unicos.py lib/node.py lib/generator/predicate_function.py lib/generator/predicate_function_declaration.py json/zanabazar_square.json
	$(PYTHON) is_zanabazar_square_unicos.py

