
all:
	make -C unico
	make -C unicos
	make -C unicoc
	make -C unicob
	make -C utf8
	make -C utf16
	make -C utf32
	
update:
	make -C unico update
	make -C unicos update
	make -C unicoc update
	make -C unicob update
	make -C utf8 update
	make -C utf16 update
	make -C utf32 update

clean:
	make -C unico clean
	make -C unicos clean
	make -C unicoc clean
	make -C unicob clean
	make -C utf8 clean
	make -C utf16 clean
	make -C utf32 clean
